# Generated by Django 3.2.9 on 2021-11-21 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_example'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsize_1',
            name='freespace',
        ),
    ]
